
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-nodes-binding
subjects:
  - kind: ServiceAccount
    name: exception-retry-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: exception-retry-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "configmaps", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-resources-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: exception-retry-sa
    namespace: default
roleRef:
  kind: Role
  name: app-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exception-retry-example-deployment
  labels:
    app: exception-retry-example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exception-retry-example-deployment
  template:
    metadata:
      name: exception-retry-example-deployment
      labels:
        app: exception-retry-example-deployment
    spec:
      securityContext: # 👈 pod-level
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      serviceAccountName: exception-retry-sa   # 👈 use SA
      volumes:
        - name: agent-volume
          emptyDir:
            medium: Memory          # 👈 uses RAM instead of disk
            sizeLimit: "768Mi"      # 👈 optional: cap memory usage
      containers:
        - name: exception-retry-example-deployment
          volumeMounts:
            - name: agent-volume
              mountPath: /agent
          resources:
            requests:
              memory: "1024Mi"  # Request 1024 MiB of memory
              cpu: "0.5"        # Request 0.5 CPU cores (500 millicores)
              ephemeral-storage: "1024Mi"   # request 256 MB
            limits:
              memory: "1536Mi"  # Limit to 1536 MiB of memory
              cpu: "1"          # Limit to 1 CPU core (1000 millicores)
              ephemeral-storage: "1024Mi"   # request 1024 MB
          image: exception-retry-example:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      restartPolicy: Always